#!/bin/bash
# Shared env bootstrap for Mastodon on Railway.
# Safe to source from web, sidekiq, and streaming entrypoints.

strip_host() {
  local value="${1:-}"
  value="${value#https://}"
  value="${value#http://}"
  value="${value#wss://}"
  value="${value#ws://}"
  value="${value%%/*}"
  printf '%s' "$value"
}

ensure_dir() {
  mkdir -p "$1" 2>/dev/null || true
}

persist_secret_file() {
  local file="$1"
  ensure_dir "$(dirname "$file")"
  umask 077
  cat >"$file" <<EOF
# Generated by mastodon-railway on first boot. Railway Variables override these.
SECRET_KEY_BASE=${SECRET_KEY_BASE:-}
OTP_SECRET=${OTP_SECRET:-}
VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY:-}
VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY:-}
ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=${ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY:-}
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=${ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY:-}
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=${ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT:-}
EOF
}

load_persisted_secrets() {
  local file="$1"
  if [ -f "$file" ]; then
    # shellcheck disable=SC1090
    set -a
    # Only fill blanks; explicit env wins.
    while IFS='=' read -r key val; do
      case "$key" in
        ''|\#*) continue ;;
      esac
      if [ -z "${!key:-}" ]; then
        export "$key=$val"
      fi
    done <"$file"
    set +a
  fi
}

generate_hex() {
  openssl rand -hex "${1:-32}"
}

bootstrap_runtime_env() {
  export RAILS_ENV="${RAILS_ENV:-production}"
  export NODE_ENV="${NODE_ENV:-production}"
  export BIND="${BIND:-0.0.0.0}"
  export RAILS_SERVE_STATIC_FILES="${RAILS_SERVE_STATIC_FILES:-true}"
  export RAILS_LOG_TO_STDOUT="${RAILS_LOG_TO_STDOUT:-true}"
  export ES_ENABLED="${ES_ENABLED:-false}"
  export LOCAL_HTTPS="${LOCAL_HTTPS:-true}"
  export TRUSTED_PROXY_IP="${TRUSTED_PROXY_IP:-127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fd00::/8}"

  if [ -z "${DATABASE_URL:-}" ] && [ -n "${POSTGRES_DATABASE_URL:-}" ]; then
    export DATABASE_URL="$POSTGRES_DATABASE_URL"
  fi

  if [ -z "${REDIS_URL:-}" ] && [ -n "${REDIS_PRIVATE_URL:-}" ]; then
    export REDIS_URL="$REDIS_PRIVATE_URL"
  fi

  if [ -z "${LOCAL_DOMAIN:-}" ]; then
    if [ -n "${RAILWAY_PUBLIC_DOMAIN:-}" ]; then
      export LOCAL_DOMAIN
      LOCAL_DOMAIN="$(strip_host "$RAILWAY_PUBLIC_DOMAIN")"
    fi
  else
    export LOCAL_DOMAIN
    LOCAL_DOMAIN="$(strip_host "$LOCAL_DOMAIN")"
  fi

  if [ -n "${WEB_DOMAIN:-}" ]; then
    export WEB_DOMAIN
    WEB_DOMAIN="$(strip_host "$WEB_DOMAIN")"
  else
    export WEB_DOMAIN="${LOCAL_DOMAIN:-}"
  fi

  if [ -z "${STREAMING_API_BASE_URL:-}" ]; then
    local streaming_host="${STREAMING_PUBLIC_DOMAIN:-}"
    if [ -z "$streaming_host" ] && [ -n "${STREAMING_RAILWAY_PUBLIC_DOMAIN:-}" ]; then
      streaming_host="$STREAMING_RAILWAY_PUBLIC_DOMAIN"
    fi
    streaming_host="$(strip_host "$streaming_host")"
    if [ -n "$streaming_host" ]; then
      export STREAMING_API_BASE_URL="wss://${streaming_host}"
    fi
  fi

  # Paperclip / media live here in official v4.7 images.
  export PAPERCLIP_ROOT_PATH="${PAPERCLIP_ROOT_PATH:-/opt/mastodon/public/system}"
}

require_var() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    echo "ERROR: missing required variable $name" >&2
    exit 1
  fi
}

wait_for_redis() {
  local tries="${1:-60}"
  if [ -z "${REDIS_URL:-}" ]; then
    echo "ERROR: REDIS_URL is not set" >&2
    exit 1
  fi
  echo "Waiting for Redis..."
  local i
  for i in $(seq 1 "$tries"); do
    if ruby -e "require 'redis'; Redis.new(url: ENV.fetch('REDIS_URL')).ping" >/dev/null 2>&1; then
      echo "Redis is ready."
      return 0
    fi
    sleep 2
  done
  echo "ERROR: Redis did not become ready" >&2
  exit 1
}

wait_for_postgres() {
  local tries="${1:-90}"
  if [ -z "${DATABASE_URL:-}" ]; then
    echo "ERROR: DATABASE_URL is not set" >&2
    exit 1
  fi
  echo "Waiting for Postgres..."
  local i
  for i in $(seq 1 "$tries"); do
    if bundle exec rails runner 'ActiveRecord::Base.connection.execute("SELECT 1")' >/dev/null 2>&1; then
      echo "Postgres is ready."
      return 0
    fi
    sleep 2
  done
  echo "ERROR: Postgres did not become ready" >&2
  exit 1
}
